# Generated by Django 2.2.9 on 2019-12-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
